### ISSUE TITLE
docs: Base64 Padding

### ISSUE THREAD

**Issue by weyung** [darkyzhou/seele#9]
In [add_file](https://seele.darkyzhou.net/tasks/files) part of docs, it says that the padding of base64 encoding need to be removed, but the **example** of the part(as follow) include "=", this is a bit confusing for me.

```yaml
steps:
  prepare:
    action: "seele/add-files@1"
    files:
      - path: "main.h"
        base64: "ZXh0ZXJuIGludCBwb3dlcjs="
      - path: "main.c"
        base64: "I2luY2x1ZGUgPHN0ZGlvLmg+CiNpbmNsdWRlICJtYWluLmgiCgppbnQgcG93ZXIgPSAxMTQ1MTQ7CgppbnQgbWFpbih2b2lkKSB7CiAgcHJpbnRmKCJQb3dlcjogJWRcbiIsIHBvd2VyKTsKICByZXR1cm4gMDsKfQ=="
```
